Algoritmo "exercício-01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler uma temperatura em graus Celsius e apresentá-la convertida
// em graus Fahrenheit. A fórmula de conversão é F  (9 * C + 160) / 5,
// sendo F a temperatura em Fahrenheit e C a temperatura em Celsius
// Autor(a)    : Ana Carolina Correa
// Data atual  : 27/09/2026
Var
// Seção de Declarações das variáveis 
temperatura, C, F: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("==========================")
Escreval("Graus Celsius e Fahrenheit")
Escreval("==========================")
Escreval("")
Escreval("Digite uma temperatura: ")
leia(C)

f <- (9 * C + 160) / 5

Escreval("Temperatura: ", F, " fahrenheit")


Fimalgoritmo