Algoritmo "exercício-29"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Ana Carolina Correa
// Data atual  : 29/09/2026
Var
// Seção de Declarações das variáveis 
valor, quadrado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("=====================")
Escreval("Quadrados de 15 a 200")
Escreval("=====================")
Escreval("")

para valor de 15 ate 200 faca
quadrado <- valor * valor
Escreval(valor, "² = ", quadrado)
fimpara


Fimalgoritmo