Algoritmo "exercício-15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar o total da soma obtida dos cem primeiros
// números inteiros (1+2+3+4+...+98+99+100
// Autor: Ana Carolina Correa
// Data atual  : 27/09/2026
Var
// Seção de Declarações das variáveis 
i, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
soma <- 0
   i <- 1

enquanto i <= 100 faca
soma <- soma + i
i <- i + 1
fimenquanto

Escreval("A soma dos 100 primeiros números inteiros é: ", soma)

Fimalgoritmo
Fimalgoritmo