Algoritmo "EXERCÍCIO-17"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ana Carolina Correa da Silva
// Data atual  : 27/09/2026
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("=================")
Escreval("Ímpares de 0 a 20")
Escreval("=================")
Escreval("")

para i de 0 ate 20 faca
se i mod 2 <> 0 entao
Escreval(i)
fimse
fimpara

Escreval("")
Escreval("Fim da listagem.")

Fimalgoritmo